mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.tsinghua.shops.mybatis.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poetize?serverTimeZone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 9090
